"""Harden domain models with unique constraints and cascades

Revision ID: 7326081b5885
Revises: f20cbe660979
Create Date: 2026-03-26 12:02:45.460093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7326081b5885'
down_revision: Union[str, Sequence[str], None] = 'f20cbe660979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_cliente_area_nombre', ['cliente_id', 'nombre'])

    with op.batch_alter_table('certificados', schema=None) as batch_op:
        pass
        # batch_op.create_unique_constraint(batch_op.f('uq_certificados_hash_verificacion'), ['hash_verificacion'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cuit'), ['cuit'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_razon_social'), ['razon_social'], unique=True)

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empleados_dni'), ['dni'], unique=False)
        batch_op.create_unique_constraint('uix_cliente_empleado_dni', ['cliente_id', 'dni'])
        # Ignoramos uid firebase aqui porque puede venir vacio y romper SQLite uniques a veces

    with op.batch_alter_table('rubros', schema=None) as batch_op:
        pass
        # batch_op.create_unique_constraint(batch_op.f('uq_rubros_nombre'), ['nombre'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubros', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_rubros_nombre'), type_='unique')

    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_constraint('uix_cliente_empleado_dni', type_='unique')
        batch_op.drop_index(batch_op.f('ix_empleados_dni'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_razon_social'))
        batch_op.drop_index(batch_op.f('ix_clientes_cuit'))

    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_certificados_hash_verificacion'), type_='unique')

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_constraint('uix_cliente_area_nombre', type_='unique')

    # ### end Alembic commands ###
