"""Add fecha_programada to CapacitacionProgramada

Revision ID: a8cb63baaca6
Revises: 0a6aeae91440
Create Date: 2026-04-01 18:10:54.736602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cb63baaca6'
down_revision: Union[str, Sequence[str], None] = '0a6aeae91440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaciones_capacitacion', schema=None) as batch_op:
        batch_op.alter_column('programada_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_asignaciones_capacitacion_programada_id_capacitaciones_programadas'), 'capacitaciones_programadas', ['programada_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('capacitaciones_programadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_programada', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capacitaciones_programadas', schema=None) as batch_op:
        batch_op.drop_column('fecha_programada')

    with op.batch_alter_table('asignaciones_capacitacion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_asignaciones_capacitacion_programada_id_capacitaciones_programadas'), type_='foreignkey')
        batch_op.alter_column('programada_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
