"""Add SessionParticipant integrity and score thresholds

Revision ID: c98ec02d5c1e
Revises: 7326081b5885
Create Date: 2026-03-26 12:17:21.501168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98ec02d5c1e'
down_revision: Union[str, Sequence[str], None] = '7326081b5885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_capacitaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntaje_aprobacion', sa.Float(), nullable=True))

    with op.batch_alter_table('sesion_participantes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_sesion_empleado_participante', ['sesion_id', 'empleado_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesion_participantes', schema=None) as batch_op:
        batch_op.drop_constraint('uix_sesion_empleado_participante', type_='unique')

    with op.batch_alter_table('catalogo_capacitaciones', schema=None) as batch_op:
        batch_op.drop_column('puntaje_aprobacion')

    # ### end Alembic commands ###
