"""add_activa_capacitacion

Revision ID: e25f784b6c04
Revises: a8cb63baaca6
Create Date: 2026-04-02 14:09:33.486560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25f784b6c04'
down_revision: Union[str, Sequence[str], None] = 'a8cb63baaca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_capacitaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_capacitaciones', schema=None) as batch_op:
        batch_op.drop_column('activa')

    # ### end Alembic commands ###
