"""Initial schema migration

Revision ID: f20cbe660979
Revises: 
Create Date: 2026-03-26 11:42:33.750566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20cbe660979'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_capacitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_horas', sa.Integer(), nullable=True),
    sa.Column('requiere_evaluacion', sa.Boolean(), nullable=True),
    sa.Column('meses_vigencia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_capacitaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_capacitaciones_id'), ['id'], unique=False)

    op.create_table('rubros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubros_id'), ['id'], unique=False)

    op.create_table('usuarios_consultora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('uid_firebase', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid_firebase')
    )
    with op.batch_alter_table('usuarios_consultora', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_consultora_id'), ['id'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('cuit', sa.String(length=50), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit'),
    sa.UniqueConstraint('razon_social')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=False)

    op.create_table('materiales_capacitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['catalogo_capacitaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materiales_capacitacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiales_capacitacion_id'), ['id'], unique=False)

    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('opciones_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['catalogo_capacitaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preguntas_id'), ['id'], unique=False)

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_id'), ['id'], unique=False)

    op.create_table('cliente_capacitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=True),
    sa.Column('obligatoria', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['catalogo_capacitaciones.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_capacitaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_capacitaciones_id'), ['id'], unique=False)

    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('dni', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('uid_firebase', sa.String(length=128), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid_firebase')
    )
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empleados_id'), ['id'], unique=False)

    op.create_table('sesiones_capacitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('capacitacion_id', sa.Integer(), nullable=True),
    sa.Column('titulo_sesion', sa.String(length=255), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('hora_programada', sa.String(length=10), nullable=True),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('capacitador', sa.String(length=255), nullable=True),
    sa.Column('estado_sesion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('origen', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['catalogo_capacitaciones.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones_capacitacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_capacitacion_id'), ['id'], unique=False)

    op.create_table('asignaciones_capacitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('origen', sa.String(length=50), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['catalogo_capacitaciones.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asignaciones_capacitacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asignaciones_capacitacion_id'), ['id'], unique=False)

    op.create_table('empleado_areas',
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], )
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_capacitacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluaciones_id'), ['id'], unique=False)

    op.create_table('rubro_capacitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('obligatoria', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['catalogo_capacitaciones.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubro_capacitaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubro_capacitaciones_id'), ['id'], unique=False)

    op.create_table('sesion_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('asignacion_id', sa.Integer(), nullable=True),
    sa.Column('estado_participacion', sa.String(length=50), nullable=True),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones_capacitacion.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_capacitacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesion_participantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesion_participantes_id'), ['id'], unique=False)

    op.create_table('intentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=True),
    sa.Column('sesion_participante_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('nota_final', sa.Float(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['sesion_participante_id'], ['sesion_participantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intentos_id'), ['id'], unique=False)

    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('intento_id', sa.Integer(), nullable=True),
    sa.Column('hash_verificacion', sa.String(length=255), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['intento_id'], ['intentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_verificacion')
    )
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificados_id'), ['id'], unique=False)

    op.create_table('respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intento_id', sa.Integer(), nullable=True),
    sa.Column('pregunta_id', sa.Integer(), nullable=True),
    sa.Column('opcion_elegida_id', sa.Integer(), nullable=True),
    sa.Column('es_correcta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['intento_id'], ['intentos.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respuestas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respuestas_id'))

    op.drop_table('respuestas')
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificados_id'))

    op.drop_table('certificados')
    with op.batch_alter_table('intentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intentos_id'))

    op.drop_table('intentos')
    with op.batch_alter_table('sesion_participantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesion_participantes_id'))

    op.drop_table('sesion_participantes')
    with op.batch_alter_table('rubro_capacitaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubro_capacitaciones_id'))

    op.drop_table('rubro_capacitaciones')
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluaciones_id'))

    op.drop_table('evaluaciones')
    op.drop_table('empleado_areas')
    with op.batch_alter_table('asignaciones_capacitacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asignaciones_capacitacion_id'))

    op.drop_table('asignaciones_capacitacion')
    with op.batch_alter_table('sesiones_capacitacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_capacitacion_id'))

    op.drop_table('sesiones_capacitacion')
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empleados_id'))

    op.drop_table('empleados')
    with op.batch_alter_table('cliente_capacitaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_capacitaciones_id'))

    op.drop_table('cliente_capacitaciones')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_id'))

    op.drop_table('areas')
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preguntas_id'))

    op.drop_table('preguntas')
    with op.batch_alter_table('materiales_capacitacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiales_capacitacion_id'))

    op.drop_table('materiales_capacitacion')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_id'))

    op.drop_table('clientes')
    with op.batch_alter_table('usuarios_consultora', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_consultora_id'))

    op.drop_table('usuarios_consultora')
    with op.batch_alter_table('rubros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubros_id'))

    op.drop_table('rubros')
    with op.batch_alter_table('catalogo_capacitaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_capacitaciones_id'))

    op.drop_table('catalogo_capacitaciones')
    # ### end Alembic commands ###
